// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOp6WAfQL7Rm-KGALYunNpBuxA2gAU9Q',
    appId: '1:801518445583:web:463b5cdaeb3ff2d0cd2f7a',
    messagingSenderId: '801518445583',
    projectId: 'lets-do-funny-stuff',
    authDomain: 'lets-do-funny-stuff.firebaseapp.com',
    storageBucket: 'lets-do-funny-stuff.appspot.com',
    measurementId: 'G-NK9DGZ7GE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_nbzcrl_MctqNqeautOX7J5FNxJTCBik',
    appId: '1:801518445583:android:d2f9e5f8b085f20ccd2f7a',
    messagingSenderId: '801518445583',
    projectId: 'lets-do-funny-stuff',
    storageBucket: 'lets-do-funny-stuff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kb5JS5bBuXRndCC00UWJS7bLOJ1JI34',
    appId: '1:801518445583:ios:45f6da34d73d7c09cd2f7a',
    messagingSenderId: '801518445583',
    projectId: 'lets-do-funny-stuff',
    storageBucket: 'lets-do-funny-stuff.appspot.com',
    iosClientId: '801518445583-sel1bujb4u8038qn76jfn3okggp65ir1.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsDoFunnyStuff',
  );
}
